{% set version = "0.4.2" %}
{% set github = "https://github.com/acidgenomics/r-acidbase" %}

package:
  name: r-acidbase
  version: "{{ version }}"

source:
  url: "{{ github }}/archive/v{{ version }}.tar.gz"
  sha256: 8259148309829f7adaa4c5abb3055ff2bae30c7875374598ba72a7b8230574d3
  
build:
  number: 0
  noarch: generic

requirements:
  host:
    # Depends:
    - r-base >=4.0
    # Imports:
    - r-acidcli >=0.1.1
    - r-acidgenerics >=0.5.18
    - r-goalie >=0.5.1
  run:
    # Depends:
    - r-base >=4.0
    # Imports:
    - r-acidcli >=0.1.1
    - r-acidgenerics >=0.5.18
    - r-goalie >=0.5.1

test:
  commands:
    - $R -e "library('AcidBase')"

about:
  home: https://r.acidgenomics.com/packages/acidbase/
  dev_url: "{{ github }}"
  license: AGPL-3.0
  license_file: LICENSE
  license_family: GPL
  summary: Low-level base functions imported by Acid Genomics packages.

extra:
  recipe-maintainers:
    - acidgenomics
    - mjsteinbaugh
