{% set name = "f5c" %}
{% set version = "0.7" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/hasindu2008/f5c/releases/download/v0.7/f5c-v0.7-release.tar.gz
  sha256: fba844c8da1fc6fca76bd61af7c4c6f9eebe15ce18351f803f4bac8cc7bbd0f5

build:
  number: 0

requirements:
  build:
    - make
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - zlib
    - hdf5
    - wget
  run:
    - zlib
    - hdf5

test:
  commands:
    - f5c --help
    - f5c --version

about:
  home: https://github.com/hasindu2008/f5c
  license: MIT
  license_file: LICENSE
  summary: 'An optimised re-implementation of the call-methylation and eventalign modules in Nanopolish.'
